# Generated by Django 4.0.3 on 2022-05-27 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prioritys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(default='不急', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Severitys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(default='不嚴重', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('Summary', models.CharField(default='Bug', max_length=10)),
                ('Description', models.TextField()),
                ('isResolve', models.BooleanField(default=False)),
                ('Priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.prioritys')),
                ('Severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.severitys')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='不願意透漏身分的人', max_length=10)),
                ('message', models.TextField()),
                ('del_pass', models.CharField(max_length=10)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.mood')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='A123456', max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('PermissionRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.permissionrole')),
            ],
        ),
    ]
